# Welcome to Jekyll!
#

# Site settings
title: More Then Now
description: |
  Hello, and welcome to Tmoas Thwh Euhusho!
owner: Brand 1
first_published: 2017 # if migrating another site, the year of your first publish
email: timmy@timmysdomain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "danm847.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/github
  github: https://github.com/github
  linkedin-square: https://linkedin.com/in/github
  facebook-official: https://facebook.com/github
  google-plus-square: https://plus.google.com/u/0/+github
  #email: /contact/
  #flickr:
  instagram: https://instagram.com/github
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
